// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDuDRZQSzSeyKExBvlegI090AMASTyrw',
    appId: '1:457596719706:web:fb01db594752f309bb3e63',
    messagingSenderId: '457596719706',
    projectId: 'sales-1242002',
    authDomain: 'sales-1242002.firebaseapp.com',
    storageBucket: 'sales-1242002.appspot.com',
    measurementId: 'G-NS7P3ZC0W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGmI9Ii1aJUSv1fST7ZOxDpUQFmwwLq8',
    appId: '1:457596719706:android:0de4c2ca1e08f227bb3e63',
    messagingSenderId: '457596719706',
    projectId: 'sales-1242002',
    storageBucket: 'sales-1242002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI76mYxzKGhNmwiLq527OEb7hj54_fN44',
    appId: '1:457596719706:ios:e52ff02355ecddc2bb3e63',
    messagingSenderId: '457596719706',
    projectId: 'sales-1242002',
    storageBucket: 'sales-1242002.appspot.com',
    iosClientId: '457596719706-n05ujjij7lndq0fsjbokk0pu2658alas.apps.googleusercontent.com',
    iosBundleId: 'com.example.sales1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI76mYxzKGhNmwiLq527OEb7hj54_fN44',
    appId: '1:457596719706:ios:e52ff02355ecddc2bb3e63',
    messagingSenderId: '457596719706',
    projectId: 'sales-1242002',
    storageBucket: 'sales-1242002.appspot.com',
    iosClientId: '457596719706-n05ujjij7lndq0fsjbokk0pu2658alas.apps.googleusercontent.com',
    iosBundleId: 'com.example.sales1',
  );
}
